# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    """
    Create unique indexes for fields inside the jsonfields in different models.

    Note that this file is not deleted during the recreate-db command.
    """

    dependencies = [
        ('metax_api', '0001_initial'),
    ]

    operations = [
        # data catalogs
        migrations.RunSQL(
            "CREATE UNIQUE INDEX IF NOT EXISTS dat_cat_ident "
            "ON metax_api_datacatalog ((catalog_json->>'identifier'));"
        ),

        # contracts
        migrations.RunSQL(
            "CREATE UNIQUE INDEX IF NOT EXISTS contract_ident "
            "ON metax_api_contract ((contract_json->>'identifier'));"
        ),

        # file storages
        migrations.RunSQL(
            "CREATE UNIQUE INDEX IF NOT EXISTS file_storage_ident "
            "ON metax_api_filestorage ((file_storage_json->>'identifier'));"
        ),
    ]
