# Generated by Django 2.1.2 on 2018-11-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0005_auto_20181101_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrecord',
            name='date_deprecated',
            field=models.DateTimeField(null=True),
        ),
    ]
