# Generated by Django 2.1.2 on 2018-11-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0006_catalogrecord_date_deprecated'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrecord',
            name='date_removed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='date_removed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='datacatalog',
            name='date_removed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='date_removed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='date_removed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='date_removed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='xmlmetadata',
            name='date_removed',
            field=models.DateTimeField(null=True),
        ),
    ]
