# Generated by Django 2.1.2 on 2018-11-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0007_auto_20181126_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='replication_path',
        ),
    ]
