# Generated by Django 2.1.2 on 2019-01-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0008_remove_file_replication_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrecord',
            name='preservation_identifier',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
