# Generated by Django 2.1.9 on 2019-06-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0009_catalogrecord_preservation_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_modified',
            field=models.DateTimeField(),
        ),
    ]
