# Generated by Django 2.1.9 on 2019-08-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0011_catalogrecord_preservation_dataset_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrecord',
            name='cumulative_state',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes'), (2, 'closed')], default=0),
        ),
        migrations.AddField(
            model_name='catalogrecord',
            name='date_cumulation_ended',
            field=models.DateTimeField(help_text='Date when cumulative_state was set to CLOSED.', null=True),
        ),
        migrations.AddField(
            model_name='catalogrecord',
            name='date_cumulation_started',
            field=models.DateTimeField(help_text='Date when cumulative_state was set to YES.', null=True),
        ),
        migrations.AddField(
            model_name='catalogrecord',
            name='date_last_cumulative_addition',
            field=models.DateTimeField(null=True, default=None, help_text='Date of last file addition while actively cumulative.')
        ),
    ]
