# Generated by Django 2.1.11 on 2019-12-16 12:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0012_auto_20190823_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrecord',
            name='_access_granter',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, help_text='Stores data of REMS user who is currently granting access to this dataset', null=True),
        ),
    ]
