# Generated by Django 2.1.11 on 2020-02-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0013_catalogrecord__access_granter'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrecord',
            name='state',
            field=models.CharField(choices=[('published', 'published'), ('draft', 'draft')], default='published', help_text='Publishing state (published / draft) of the dataset.', max_length=200),
        ),
    ]
