# Generated by Django 2.2.10 on 2020-03-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0017_catalogrecord_rems_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogrecord',
            old_name='_access_granter',
            new_name='access_granter',
        ),
    ]
