# Generated by Django 2.2.10 on 2020-04-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0018_auto_20200330_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogRecordV2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('metax_api.catalogrecord',),
        ),
        migrations.AlterField(
            model_name='catalogrecord',
            name='state',
            field=models.CharField(choices=[('published', 'published'), ('draft', 'draft')], default='draft', help_text='Publishing state (published / draft) of the dataset.', max_length=200),
        ),
    ]
