# Generated by Django 2.2.10 on 2020-05-18 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0020_auto_20200429_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrecord',
            name='next_draft',
            field=models.OneToOneField(help_text='A draft of the next changes to be published on this dataset, in order to be able to save progress, and continue later. Is created from a published dataset. When the draft is published, changes are saved on top of the original dataset, and the draft record is destroyed.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='draft_of', to='metax_api.CatalogRecord'),
        ),
    ]
