# Generated by Django 2.2.10 on 2020-05-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0021_catalogrecord_next_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacatalog',
            name='catalog_record_group_read',
            field=models.CharField(help_text='Group which is allowed to read catalog records in the catalog.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datacatalog',
            name='catalog_record_services_read',
            field=models.CharField(help_text='Services which are allowed to read catalog records in the catalog.', max_length=200, null=True),
        ),
    ]
