# Generated by Django 3.0.7 on 2020-07-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0023_catalogrecord_api_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrecord',
            name='use_doi_for_draft',
            field=models.BooleanField(blank=True,
                                      default=None,
                                      help_text='Is True when "Use_DOI" field is checked in Qvain Light for draft.',
                                      null=True),
        ),
    ]
