# Generated by Django 3.0.7 on 2020-10-13 11:04

from django.db import migrations
import csv
import json
import logging

logger = logging.getLogger(__name__)

def rename(apps, schema_editor):
    CatalogRecord = apps.get_model('metax_api', 'CatalogRecord')

    # Loop through csv
    try:
        with open('metax_api/migrations/datasets/SYKE_csv.csv', newline='') as csvfile:
            reader = csv.DictReader(csvfile, delimiter=";", quotechar='"')

            for row in reader:
                old_guid = row["vanha guid"]

                if old_guid == 'vanha guid': # Check if is heade value
                    pass
                else:
                    # Get dataset
                    try:
                        cr = CatalogRecord.objects.get(research_dataset__other_identifier__0__notation = old_guid)
                        new_guid = row["uusi guid"]
                        cr.research_dataset['other_identifier'][0]['notation'] = new_guid
                        cr.research_dataset['other_identifier'][0]['old_notation'] = old_guid
                        cr.user_modified = "migration_0027"
                        cr.save()
                        logger.info(f"successful migration of cr {cr.id} with new guid {new_guid} and old guid {old_guid}")
                    except CatalogRecord.DoesNotExist:
                        pass
    except FileNotFoundError as e:
        logger.error(f"syke csv not found: {e}")

def revert(apps, schema_editor):
    CatalogRecord = apps.get_model('metax_api', 'CatalogRecord')
    modified = CatalogRecord.objects.filter(user_modified="migration_0027")
    for cr in modified:
        try:
            o_ids = cr.research_dataset['other_identifier']
            if "old_notation" in o_ids[0].keys():
                cr.research_dataset['other_identifier'][0]['notation'] = o_ids[0]["old_notation"]
                del cr.research_dataset['other_identifier'][0]['old_notation']
                cr.save()
        except CatalogRecord.DoesNotExist:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0026_auto_20200917_1615'),
    ]

    operations = [
        migrations.RunPython(rename, revert),
    ]
