# Generated by Django 3.0.7 on 2020-10-20 07:10

import logging

from django.db import migrations

_logger = logging.getLogger(__name__)

class Migration(migrations.Migration):

    def remove_empty_format_version(apps, schema_editor):
        import json
        File = apps.get_model('metax_api', 'File')

        _logger.info('Checking for empty format_version values..')
        scanned_rows = File.objects.filter(file_characteristics__format_version="").count()
        _logger.info(f"query size: {scanned_rows}")
        for f in File.objects.filter(file_characteristics__format_version=""):

            file_changed = False
            if f.file_characteristics:
                filedata = json.loads(json.dumps(f.file_characteristics))
                if 'format_version' in filedata:
                    filedata.pop('format_version', None)
                    file_changed = True

            if file_changed:
                f.file_characteristics = filedata
                f.save()

    def revert(apps, schema_editor):
        pass

    dependencies = [
        ('metax_api', '0027_auto_20201013_1404'),
    ]

    operations = [
        migrations.RunPython(remove_empty_format_version, revert),
    ]
