# Generated by Django 3.1.2 on 2020-11-03 10:33
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0029_auto_20201028_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogrecord',
            name='_directory_data',
            field=models.JSONField(help_text='Stores directory data related to browsing files and directories', null=True),
        ),
        migrations.AlterField(
            model_name='catalogrecord',
            name='access_granter',
            field=models.JSONField(default=None, help_text='Stores data of REMS user who is currently granting access to this dataset', null=True),
        ),
        migrations.AlterField(
            model_name='catalogrecord',
            name='api_meta',
            field=models.JSONField(default=dict, help_text='Saves api related info about the dataset. E.g. api version', null=True),
        ),
        migrations.AlterField(
            model_name='catalogrecord',
            name='dataset_version_set',
            field=models.ForeignKey(help_text='Records which are different dataset versions of each other.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='metax_api.datasetversionset'),
        ),
        migrations.AlterField(
            model_name='catalogrecord',
            name='editor',
            field=models.JSONField(help_text='Editor specific fields, such as owner_id, modified, record_identifier', null=True),
        ),
        migrations.AlterField(
            model_name='catalogrecord',
            name='next_draft',
            field=models.OneToOneField(help_text='A draft of the next changes to be published on this dataset, in order to be able to save progress, and continue later. Is created from a published dataset. When the draft is published, changes are saved on top of the original dataset, and the draft record is destroyed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_of', to='metax_api.catalogrecord'),
        ),
        migrations.AlterField(
            model_name='catalogrecord',
            name='research_dataset',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacatalog',
            name='catalog_json',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_characteristics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_characteristics_extension',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='file_storage_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metaxuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='researchdatasetversion',
            name='research_dataset',
            field=models.JSONField(),
        ),
    ]