# Generated by Django 3.1.2 on 2020-12-07 09:17
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0030_auto_20201103_1233'),
        ('metax_api', '0030_kotus_datasets'),
    ]

    operations = [
    ]