# Generated by Django 3.1.2 on 2021-02-01 13:51
import logging

from django.db import migrations

logger = logging.getLogger(__name__)

def recount_directory_files(apps, schema_editor):
    Directory = apps.get_model('metax_api', 'Directory')
    dirs_with_no_files = Directory.objects.filter(file_count=0, parent_directory_id=None)
    logger.info(f"found {dirs_with_no_files.count()} directories without files")
    aff_rows = 0
    for dir in dirs_with_no_files:
        dir.calculate_byte_size_and_file_count()
        aff_rows += 1
    logger.info(f"migration 0033 complete with {aff_rows} affected rows")


def revert(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0032_auto_20201222_1321'),
    ]

    operations = [
        migrations.RunPython(recount_directory_files, revert),
    ]
