# Generated by Django 3.1.8 on 2021-06-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0033_auto_20210201_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiError',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=200, unique=True)),
                ('error', models.JSONField()),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
