# Generated by Django 3.1.12 on 2021-08-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0035_auto_20210804_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedobject',
            name='identifier',
        ),
    ]
