# Generated by Django 3.1.12 on 2021-08-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0036_remove_deletedobject_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedobject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
