# Generated by Django 3.1.12 on 2021-08-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0037_auto_20210811_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogrecord',
            name='editor',
        ),
    ]
