# Generated by Django 3.1.13 on 2021-09-08 08:51
import json

from django.db import migrations

import logging

logger = logging.getLogger(__name__)

datasets = [
    "1acea3cc-c245-4f6d-80ee-f9c6a6c907be",
    "72dc2050-70bc-4f46-9fc7-b3ac2bd58bdc",
    "9341625d-ebbb-4625-a2db-6c0424cdcf85",
    "4a66600c-79b2-4dcf-a497-69540b4d0817",
    "51c7c6c4-0129-4856-be71-072582882cb5",
    "56ab6296-9bc9-41b3-95ea-b4655aa7978b",
    "66cc0770-08f9-4df3-ac6f-b65a15f5e73e",
]

"""
Changes:

metadata_provider_user: tuokalma
to ->
metadata_provider_user: ksuomine

access_granter:
name: Alma Tuokko
email: alma.tuokko@helsinki.fi
userid: tuokalma
to ->
access_granter:
name: Karina Lukin
email: karina.lukin@helsinki.fi
userid: ksuomine
"""

def change_metadata_provider_user(apps, schema_editor):
    CatalogRecord = apps.get_model('metax_api', 'CatalogRecord')
    for cr in CatalogRecord.objects.filter(identifier__in=datasets):
        try:
            if cr.metadata_provider_user:
                provider_usr = json.loads(json.dumps(cr.metadata_provider_user))
                changed_usr = provider_usr.replace("tuokalma", "ksuomine")
                cr.metadata_provider_user = changed_usr

            if cr.access_granter:
                access_granter = json.loads(json.dumps(cr.access_granter))
                changed_granter = access_granter.replace("Alma Tuokko", "Karina Lukin")
                changed_granter = changed_granter.replace("alma.tuokko@helsinki.fi", "karina.lukin@helsinki.fi")
                changed_granter = changed_granter.replace("tuokalma", "ksuomine")
                cr.access_granter = changed_granter

            cr.save()
        except Exception as e:
            logger.error(e)


def revert(apps, schema_editor):
    CatalogRecord = apps.get_model('metax_api', 'CatalogRecord')
    for cr in CatalogRecord.objects.filter(identifier__in=datasets):
        try:
            if cr.metadata_provider_user:
                provider_usr = json.loads(json.dumps(cr.metadata_provider_user))
                changed_usr = provider_usr.replace("ksuomine", "tuokalma")
                cr.metadata_provider_user = changed_usr

            if cr.access_granter:
                access_granter = json.loads(json.dumps(cr.access_granter))
                changed_granter = access_granter.replace("Karina Lukin", "Alma Tuokko")
                changed_granter = changed_granter.replace("karina.lukin@helsinki.fi", "alma.tuokko@helsinki.fi")
                changed_granter = changed_granter.replace("ksuomine", "tuokalma")
                cr.access_granter = changed_granter

            cr.save()
        except Exception as e:
            logger.error(e)

class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0038_remove_catalogrecord_editor'),
    ]

    operations = [
        migrations.RunPython(change_metadata_provider_user, revert),
    ]