# Generated by Django 3.1.13 on 2021-08-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0038_add_editorpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogrecord',
            name='editor_permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_records', to='metax_api.editorpermissions'),
        ),
    ]
