# Generated by Django 3.1.13 on 2021-11-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0042_auto_20211108_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editoruserpermission',
            name='verified',
        ),
    ]
