# Generated by Django 3.2.10 on 2021-12-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0044_change_aalto_catalog_to_harvested'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationStatistics',
            fields=[
                ('organization', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('byte_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatistics',
            fields=[
                ('project_identifier', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('byte_size', models.IntegerField()),
                ('published_datasets', models.TextField()),
            ],
        ),
    ]
