# Generated by Django 3.2.10 on 2022-04-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0048_organizationstatistics_projectstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationstatistics',
            name='byte_size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='projectstatistics',
            name='byte_size',
            field=models.BigIntegerField(),
        ),
    ]
