# Generated by Django 3.2.10 on 2022-08-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0053_home_organization_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectstatistics',
            old_name='byte_size',
            new_name='ida_byte_size',
        ),
        migrations.RenameField(
            model_name='projectstatistics',
            old_name='count',
            new_name='ida_count',
        ),
        migrations.RenameField(
            model_name='projectstatistics',
            old_name='published_datasets',
            new_name='ida_published_datasets',
        ),
        migrations.AddField(
            model_name='projectstatistics',
            name='pas_byte_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectstatistics',
            name='pas_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectstatistics',
            name='pas_published_datasets',
            field=models.TextField(default=''),
        ),
    ]
