# Generated by Django 3.2.10 on 2022-08-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0055_auto_20220815_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pas_compatible',
            field=models.BooleanField(default=True),
        ),
    ]
