# Generated by Django 3.2.10 on 2024-11-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax_api', '0067_catalog_permissions_for_metax_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogrecord',
            name='pid_migrated',
            field=models.DateTimeField(default=None, help_text='DateTimeField that saves the timestamp when the PID has been migrated to PID MS', null=True),
        ),
    ]
