workflow:
  name: '$PIPELINE_NAME'
  rules:
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/
      variables:
        PIPELINE_NAME: 'Manual pipeline to $GITLAB_ENV'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        PIPELINE_NAME: 'MR pipeline'
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
      variables:
        PIPELINE_NAME: 'Commit pipeline'

# ------------------------

variables:
  GITLAB_ENV:
    description: 'Which environment do you want to deploy to?'
    value: 'test'
    options:
      - 'staging'
      - 'test'
      - 'demo'
      - 'stable'
  SERVICE: ${SERVICE}

default:
  tags:
    - shell

stages:
  - deploy
  - update
  - test
  - e2e-test

include:
  - project: fairdata/fairdata-ci
    ref: master
    file:
      - /templates/deploy/deploy-jobs.yaml
      - /templates/test/test-jobs.yaml
      - templates/test/metax-tests.yaml

# ------------------------

deploy:
  extends: .deploy-job
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

deploy-feature:
  extends: .deploy-feature-job
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

update-proxy:
  stage: update
  environment: $GITLAB_ENV
  script:
    - ansible-playbook -i $ANSIBLE_INVENTORY $UPDATE_PROXY_PLAYBOOK --vault-id $ANSIBLE_VAULT_FILE
    - ansible-playbook -i $ANSIBLE_INVENTORY $MANAGE_PLAYBOOK --vault-id $ANSIBLE_VAULT_FILE
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

update-proxy-feature:
  stage: update
  environment: staging
  script:
    - ansible-playbook -i $ANSIBLE_INVENTORY $UPDATE_PROXY_PLAYBOOK --vault-id $ANSIBLE_VAULT_FILE
    - ansible-playbook -i $ANSIBLE_INVENTORY $MANAGE_PLAYBOOK --vault-id $ANSIBLE_VAULT_FILE
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# ------------------------

integration-test-docker:
  extends: .integration-test-docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

integration-test:
  stage: test
  environment: $GITLAB_ENV
  needs: [update-proxy]
  script:
    - ansible-playbook -i $ANSIBLE_INVENTORY $TEST_PLAYBOOK --vault-id $ANSIBLE_VAULT_FILE
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

sonarqube:
  extends: .sonarqube-job
  needs:
    - job: integration-test-docker
      artifacts: true
      optional: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/

fairdata-e2e:
  stage: e2e-test
  trigger: fairdata/fairdata-ci
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

fairdata-e2e-feature:
  stage: e2e-test
  trigger: fairdata/fairdata-ci
  variables:
    GITLAB_ENV: staging
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
