version: "3.8"

services:
  metax-web:
    image: fairdata-docker.artifactory.ci.csc.fi/fairdata-metax-web
    hostname: metax-web
    ports:
      - 8008:8008
      - 8000:8000
    environment:
      DEBUG: 'true'
      METAX_DATABASE: metax_db_test
      METAX_DATABASE_PASSWORD: YMDLekQMqrVKcs3
      METAX_DATABASE_USER: metax_test
      METAX_DATABASE_HOST: metax-db
      ELASTIC_SEARCH_HOSTS: metax-elasticsearch
      RABBIT_MQ_HOSTS: metax-rabbitmq
      REDIS_HOST: metax-redis
    volumes:
      - ./src:/code
    stdin_open: True
    tty: True

  metax-redis:
    image: redis
    hostname: metax-redis
    volumes:
      - metax-redis:/data

  metax-db:
    image: postgres:9
    hostname: metax-db
    environment:
      POSTGRES_USER: metax_test
      POSTGRES_PASSWORD: YMDLekQMqrVKcs3
      POSTGRES_DB: metax_db_test
    volumes:
      - metax-postgres:/var/lib/postgresql/data

  metax-elasticsearch:
    image: elasticsearch:7.9.2
    hostname: metax-elasticsearch
    environment:
      discovery.type: single-node
    volumes:
      - metax-es:/usr/share/elasticsearch/data

  metax-rabbitmq:
    image: rabbitmq:3-management
    hostname: metax-rabbitmq
    volumes:
      - metax-rabbitmq:/var/lib/rabbitmq

  metax-docs:
    image: fairdata-docker.artifactory.ci.csc.fi/fairdata-metax-sphinx
    hostname: metax-docs
    environment:
      DOMAIN: 0.0.0.0:8008
      REMS_ENABLED: true
    ports:
      - 8088:8000
    volumes:
      - ./docs/api:/sphinx

volumes:
  metax-rabbitmq:
    external: true
  metax-es:
    external: true
  metax-postgres:
    external: true
  metax-redis:
    external: true
