version: "3.8"

services:
  metax:
    image: fairdata-docker.artifactory.ci.csc.fi/fairdata-metax-web
    ports:
      - 8008:8008
      - 8000:8000
    volumes:
      - ./src:/code
    environment:
      DEBUG: 'true'
      METAX_DATABASE: 'metax_db_test'
      METAX_DATABASE_PASSWORD: 'YMDLekQMqrVKcs3'
      METAX_DATABASE_USER: 'metax_test'
      REDIS_HOST: metax-redis
      RABBIT_MQ_HOSTS: metax-rabbitmq
      ELASTIC_SEARCH_HOSTS: metax-elasticsearch
      METAX_DATABASE_HOST: metax-db

  metax-redis:
    image: redis
    volumes:
      - metax-redis:/data
  metax-db:
    image: postgres:9
    environment:
      POSTGRES_USER: 'metax_test'
      POSTGRES_PASSWORD: 'YMDLekQMqrVKcs3'
      POSTGRES_DB: 'metax_db_test'
    volumes:
      - metax-postgres:/var/lib/postgresql/data
  metax-elasticsearch:
    image: elasticsearch:7.9.2
    environment:
      discovery.type: 'single-node'
    volumes:
      - metax-es:/usr/share/elasticsearch/data
  metax-rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - metax-rabbitmq:/var/lib/rabbitmq

volumes:
  metax-rabbitmq:
    external: true
  metax-es:
    external: true
  metax-postgres:
    external: true
  metax-redis:
    external: true



