swagger: '2.0'
info:
  title: METAX dataset API
  version: v1
host: dataset.metax.example.org
schemes:
  - https
basePath: /rest/v1/
produces:
  - application/json
paths:
  /dataset/:
    post:
      summary: create new dataset metadata (request body JSON object with dataset metadata, without PID)
      consumes:
        - application/json
      responses:
        '201':
          description: new dataset metadata created, return Location with the new URL containing PID
  /dataset/{PID}:
    get:
      summary: get dataset metadata
      parameters:
        - name: PID
          in: path
          description: Persistent ID of dataset
          required: true
          type: string
      responses:
        '200':
          description: return dataset metadata
    put:
      summary: replace dataset metadata
      parameters:
        - name: PID
          in: path
          description: Persistent ID of dataset
          required: true
          type: string
      responses:
        '204':
          description: successful operation, no content returned
    patch:
      summary: replace part of dataset metadata
      parameters:
        - name: PID
          in: path
          description: Persistent ID of dataset
          required: true
          type: string
      responses:
        '200':
          description: successful operation, full content returned

  # for TPAS usage only
  /list_datasets:
    get:
      summary: "list datasets by owner organization and/or by TPAS state"
      parameters:
        - name: organization
          in: query
          description: owner organization ID
          required: false
          type: string
        - name: state
          in: query
          description: TPAS state (proposed for midterm PAS / proposed for longterm PAS / in packaging / in dissemination / in midterm PAS / in longterm PAS)
          required: false
          type: string
      responses:
        "200":
          description: successful operation, return list of datasets containing PID, name, owner org, argument for PAS storage, name of proposer, TPAS state, contract PID, size of dataset, structure (folders) of dataset, provenance, descriptive metadata, access rights metadata, TPAS SIP ID (METSOBJID)



