version: "3.8"

services:
  fairdata-nginx:
    image: nginx:latest
    configs:
      - source: fairdata-nginx-config
        target: /etc/nginx/nginx.conf
      - source: fairdata-ssl-certificate
        target: /etc/pki/tls/certs/ssl.crt.pem
      - source: fairdata-ssl-certificate-key
        target: /etc/pki/tls/private/ssl.key.pem
      - source: metax-nginx-config
        target: /etc/nginx/sites-enabled/metax
    ports:
      - 443:443

configs:
  metax-nginx-config:
    external: True
  fairdata-ssl-certificate:
    external: True
  fairdata-ssl-certificate-key:
    external: True
  fairdata-nginx-config:
    external: True
