from metax_api.settings.components.common import env

ELASTICSEARCH = {
    "HOSTS": env("ELASTIC_SEARCH_HOSTS"),
    "PORT": env("ELASTIC_SEARCH_PORT"),
    "USE_SSL": env("ELASTIC_SEARCH_USE_SSL"),
}

ALWAYS_RELOAD_REFERENCE_DATA_ON_RESTART = env("ALWAYS_RELOAD_REFERENCE_DATA_ON_RESTART")
# Used if ALWAYS_RELOAD_REFERENCE_DATA_ON_RESTART is False
REFERENCE_DATA_RELOAD_INTERVAL = 86400

ES_CONFIG_DIR = env("ES_CONFIG_DIR")
