from metax_api.settings.environments import test

API_TEST_USER = test.API_TEST_USER
API_METAX_USER = test.API_METAX_USER
API_AUTH_TEST_USER = test.API_AUTH_TEST_USER
API_EXT_USER = test.API_EXT_USER
API_TEST_USERS = test.API_TEST_USERS
API_ACCESS = test.API_ACCESS
ADDITIONAL_USER_PROJECTS_PATH = test.ADDITIONAL_USER_PROJECTS_PATH
